---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mitsu3s.dev
  resources:
  - overrideleases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mitsu3s.dev
  resources:
  - overrideleases/finalizers
  verbs:
  - update
- apiGroups:
  - mitsu3s.dev
  resources:
  - overrideleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - patch
